version: "3.7"

services:

  postgres:
    image: postgres:latest
    ports:
      - "0.0.0.0:5433:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: laravel-log-visits
  mysql:
    image: mysql:latest
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: laravel-log-visits
  redis:
    image: redis:latest
    sysctls:
      - net.core.somaxconn=511
    ports:
      - "0.0.0.0:6378:6379"
