name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 8.0]
        laravel: [8.*]
        stability: [prefer-stable, prefer-lowest]
        include:
          - laravel: 8.*
            testbench: ^6.23

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432
        env:
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: postgres
          POSTGRES_DB: laravel-log-visits

      mysql:
        image: mysql:latest
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: 12345
          MYSQL_DATABASE: laravel-log-visits

      redis:
        image: redis:latest
        ports:
          - 6379


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pdo_pgsql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests with pgsql
        run: vendor/bin/pest
        env:
          DB_CONNECTION: pgsql
          DB_USERNAME: postgres
          DB_PASSWORD: 12345
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}

      - name: Execute tests with mysql
        run: vendor/bin/pest
        env:
          DB_CONNECTION: mysql
          DB_USERNAME: root
          DB_PASSWORD: 12345
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
